# Generated by Django 3.1.5 on 2021-01-29 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('long_version', models.URLField()),
                ('short_version', models.CharField(max_length=155, unique=True)),
                ('re_path', models.CharField(blank=True, default=None, max_length=100)),
                ('redirect_count', models.PositiveBigIntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_browser', models.CharField(max_length=255)),
                ('client_device', models.CharField(max_length=255)),
                ('client_ip', models.CharField(max_length=15)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited', to='url_shortener.url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
